config/routes.rb
Pumpkin::Application.routes.draw do
  resources :transactions, :except => [:show, :new] do
  	get :search, :on => :collection
  end
  resources :consumers, :except => :show
  resources :boiler_rooms, :except => :show
  
  root :to => "transactions#index"
end

app/models/boiler_room.rb
# encoding: UTF-8
class BoilerRoom < ActiveRecord::Base
	has_many :transactions
	default_scope :order => 'created_at DESC'

	validates :name, :presence => :true
	
end

app/models/consumer.rb
# encoding: UTF-8
class Consumer < ActiveRecord::Base
	has_many :transactions    
	default_scope :order => 'created_at DESC'

	validates :name, :presence => :true
end

app/models/transaction.rb
# encoding: UTF-8
class Transaction < ActiveRecord::Base

	belongs_to :boiler_room
	belongs_to :consumer

	default_scope :order => 'created_at DESC'
	scope :finish, where(:status => 'finish')
	scope :use, where(:status => 'use')
	scope :sending, where(:status => 'send')
	scope :received, where(:status => 'received')


	validates :value, presence: { :on => :create }

	after_create :add_total_values
	after_destroy :destroy_total_values

	def add_total_values
		self.consumer.total += self.value
		self.boiler_room.total += self.value
		self.consumer.save  && self.boiler_room.save
	end
	
	def destroy_total_values
		self.consumer.total -= self.value
		self.boiler_room.total -= self.value
		self.consumer.save  && self.boiler_room.save
	end
	
	#CSV support
  comma  do
  	boiler_room :name => "Котельная"
  	consumer :name  => "Потребитель"
  	value "Размер поставки"
  	title "Комментарий"
  	status "Статус"
    created_at "Created at"
  end

end

app/controllers/application_controller.rb
# encoding: UTF-8
class ApplicationController < ActionController::Base
  protect_from_forgery

  before_filter :new_data

  def new_data
  	@transaction = Transaction.new
    @consumer = Consumer.new
    @boiler_room = BoilerRoom.new
  end
end

app/controllers/boiler_rooms_controller.rb
# encoding: UTF-8
class BoilerRoomsController < ApplicationController

  respond_to :html
  
  def index
    @boiler_rooms = BoilerRoom.all
  end
  
  def edit
    @boiler_room = BoilerRoom.find(params[:id])
  end

  def create
    @boiler_room = BoilerRoom.new(params[:boiler_room])
    if @boiler_room.save
      redirect_to boiler_rooms_path
    else
      render :action => :index 
    end
  end

  def update
    @boiler_room = BoilerRoom.find(params[:id])
    if @boiler_room.update_attributes(params[:boiler_room])
      redirect_to boiler_rooms_path
    end
  end

  def destroy
    @boiler_room = BoilerRoom.find(params[:id])
    @boiler_room.transactions.destroy_all
    if @boiler_room.destroy
      redirect_to boiler_rooms_path
    end
  end

end

app/controllers/consumers_controller.rb
# encoding: UTF-8
class ConsumersController < ApplicationController
  
  respond_to :html

  def index
    @consumers = Consumer.all
  end
  
  def create
    @consumer = Consumer.new(params[:consumer])
    if @consumer.save
     redirect_to consumers_path()
    else
     render :action => :index
    end
  end

  def update
    @consumer = Consumer.find(params[:id])
    if @consumer.update_attributes(params[:consumer])
      redirect_to consumers_path()
    else  
      render :action => :index
    end
  end

  def destroy
    @consumer = Consumer.find(params[:id])
    @consumer.transactions.destroy_all
    if @consumer.destroy
      redirect_to consumers_path
    end
  end

end

app/controllers/transactions_controller.rb
# encoding: UTF-8
class TransactionsController < ApplicationController

  respond_to :html, :expect => :search

  def index
    if params[:status]
      case params[:status]
        when 'send'
          @transactions = Transaction.sending
        when 'finish'
          @transactions = Transaction.finish
        when 'use'
          @transactions = Transaction.use
        when 'received'
          @transactions = Transaction.received
        else
          @transactions = Transaction.all
      end
    else
      @transactions = Transaction.all
    end
  end

  def search
    @search = Transaction.search(params[:search])
    @transactions = @search.all  
    respond_to do |format|
      format.html
      format.csv { render :csv => @transactions, :filename => "transactions" }
    end
  end
  
  def create
    @transaction = Transaction.new(params[:transaction])
    if @transaction.save
      redirect_to transactions_path()
    else
      render :action => :index
    end
  end

  def update
    @transaction = Transaction.find(params[:id])
    if @transaction.update_attributes(params[:transaction])
      redirect_to transactions_path()
    else
      render :action => :index
    end
  end

  def destroy
    @transaction = Transaction.find(params[:id])
    @transaction.destroy
    redirect_to transactions_path()
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boiler_rooms_helper.rb
module BoilerRoomsHelper
end

app/helpers/consumers_helper.rb
module ConsumersHelper
end

app/helpers/transactions_helper.rb
# encoding: UTF-8
module TransactionsHelper
	def show_status(status)
		case status
			when "send" 
				"<span class='label'>Отправлено</span>".html_safe
			when "received"
				"<span class='label success'>Получено</span>".html_safe
			when "use"
				"<span class='label warning'>Расходуется</span>".html_safe
			when "finish"
				"<span class='label important'>Израсходовано</span>".html_safe	
		end
	end
end

app/views/boiler_rooms/_form.html.erb
<%= form_for(boiler_room) do |f| %>
  <div class="clearfix">
	  <div class="input">
      <%= f.text_field :name, :placeholder => "Имя"%>
	</div>
  </div>
  <div class="actions">
	<% if create%>
		<%= f.submit 'Добавить', :class => "btn primary"%>
	<% else %>	
		<%= f.submit 'Обновить', :class => "btn primary"%>
	<% end %>
  </div>
<% end %>

app/views/boiler_rooms/index.html.erb
<table class="zebra-striped" id="boiler_rooms">
<thead>
  <tr>
	 	<th>Котельная</th>
	 	<th>Отправлено всего</th>
	 	<th></th>
	 	<th></th>
  </tr>
</thead>
 <tbody>
<% @boiler_rooms.each do |boiler_room| %>
  <tr>
    <td><%= boiler_room.name%></td>
    <td><%= boiler_room.total%> м<sup>3</sup></td>
    <td>
		<div id="modal-from-dom<%=boiler_room.id%>" class="modal hide fade">
			<div class="modal-header">
				<a href="#" class="close">&times;</a>
				<h3>Редактировать котельную</h3>
			</div>
			<div class="modal-body">
				<%= render "form", :boiler_room => boiler_room, :create => false %>	
			</div>
		</div>
		<%= button_to 'Редактировать', edit_boiler_room_path(boiler_room),{:method => :get, :class => "btn","data-backdrop" => true,
																			"data-controls-modal" => "modal-from-dom#{boiler_room.id}",
																			"data-keyboard" => true } %>
	</td>
	<td>
		<%= button_to 'Удалить', boiler_room, :confirm => 'Вы уверены?', :method => :delete, :class => "btn danger" %>
	</td>
  </tr>
<% end %>
 </tbody>
</table>

app/views/consumers/_form.html.erb
<%= form_for(consumer) do |f| %>
  <div class="clearfix">
	<div class="input">
    	<%= f.text_field :name, :placeholder => "Имя"%>
	</div>	
  </div>
  <div class="actions">
	<% if create %>
    	<%= f.submit "Добавить", :class => "btn primary" %>
	<% else %>
		<%= f.submit "Обновить", :class => "btn primary" %>
	<% end%>
  </div>
<% end %>

app/views/consumers/index.html.erb
<table class="zebra-striped" id="consumers">
  <thead>	
  <tr>
    <th>Потребитель</th>
    <th>Получено всего</th>
    <th></th>
    <th></th>
  </tr>
  </thead>
<tbody>
<% @consumers.each do |consumer| %>
  <tr>
    <td><%= consumer.name %></td>
    <td><%= consumer.total%> м<sup>3</sup></td>
    <td>
		<div id="modal-from-dom<%=consumer.id%>" class="modal hide fade">
			<div class="modal-header">
				<a href="#" class="close">&times;</a>
				<h3>Редактировать потребителя</h3>
			</div>
			<div class="modal-body">
				<%= render "form", :consumer => consumer, :create => false %>	
			</div>
		</div>
		<%= button_to 'Редактировать', "#",{:method => :get, :class => "btn",
										"data-backdrop" => true,
										"data-controls-modal" => "modal-from-dom#{consumer.id}",
										"data-keyboard" => true } %>
									</td>
    <td><%= button_to 'Удалить', consumer, :confirm => 'Вы уверены', :method => :delete, :class => "btn danger" %></td>
  </tr>
<% end %>
</tbody>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Система автоматизации учета поставок топлива для котельних</title>
  <%= stylesheet_link_tag  "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="topbar" data-dropdown="dropdown">
    <div class="topbar-inner">
		<div class="container">
			<%=link_to "Pumpkin", root_path(), :class =>"brand" %>
			<ul class="nav">
			    <li id="transactions"><%=link_to "Поставки", transactions_path()%></li>
				  <li id="boiler_rooms"><%=link_to "Котельные", boiler_rooms_path()%></li>
          <li id="consumers"><%=link_to "Потребители", consumers_path()%></li>
          <li id="search"><%= link_to "Поиск", search_transactions_path()%></li>
      </ul>
      <ul class="nav secondary-nav">
          <li class="dropdown">
             		 <a href="#" class="dropdown-toggle"><span style="font-size:17px;">Добавить</span></a>
              		 <ul class="dropdown-menu">
                    <li><a href="#" data-controls-modal="modal-transaction" data-backdrop="true" data-keyboard="true">Поставку</a></li>
                    <li class="divider"></li>
                	 	<li><a href="#" data-controls-modal="modal-consumer" data-backdrop="true" data-keyboard="true">Потребителя</a></li>
               			<li><a href="#" data-controls-modal="modal-boiler_room" data-backdrop="true" data-keyboard="true">Котельную</a></li>
              		</ul>
          </li>
			</ul>
		</div>
	</div>
</div>
<div class="container" style="padding-top: 60px;">
	<%= yield %>	
  <div id="modal-transaction" class="modal hide fade">
  <div class="modal-header">
    <a href="#" class="close">&times;</a>
    <h3 style="text-align:center;">Новая поставка</h3>
  </div>
  <div class="modal-body">
    <%= render "transactions/form", :transaction => @transcation %> 
  </div>
</div>
<div id="modal-consumer" class="modal hide fade">
  <div class="modal-header">
    <a href="#" class="close">&times;</a>
    <h3 style="text-align:center;">Новый потребитель</h3>
  </div>
  <div class="modal-body">
    <%= render "consumers/form", :consumer => @consumer, :create => :true %> 
  </div>
</div>
<div id="modal-boiler_room" class="modal hide fade">
  <div class="modal-header">
    <a href="#" class="close">&times;</a>
    <h3 style="text-align:center;">Новая котельная</h3>
  </div>
  <div class="modal-body">
    <%= render "boiler_rooms/form", :boiler_room => @boiler_room, :create => :true %> 
  </div>
</div>
<footer>
	<p>&copy; ОАО "ЖилГорСтрой" 2011</p>
</footer>	
</div>	
</body>
</html>

app/views/transactions/_change_status_form.html.erb
<%= form_for transaction, :action => :update do |f| %>
  <div class="clearfix">
      <div class="input">
        <%= f.select :status, [["Отправлено","send" ],["Получено", "received"],["Расходуется", "use"],["Израсходовано", "finish"]] %>
      </div>
  </div>
   <div class="clearfix">
      <div class="input">
        <%= f.text_field :title, :placeholder => "Комментарий" %>
      </div>
  </div>
  <div class="actions">
     <%= f.submit "Поменять", :class => "btn primary" %>
  </div>  
<% end %>

app/views/transactions/_form.html.erb
<%= form_for @transaction, :validate => true do |f| %>
  <% if @transaction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@transaction.errors.count, "error") %> prohibited this transaction from being saved:</h2>

      <ul>
      <% @transaction.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="clearfix">
      <div class="input">
        <%= f.select :boiler_room_id, BoilerRoom.all.collect {|b| [ b.name, b.id ]} %>
      </div>
  </div>
  <div class="clearfix">
      <div class="input">
        <%= f.select :consumer_id, Consumer.all.collect {|c| [ c.name, c.id ]} %>
      </div>
  </div>
   <div class="clearfix">
    <div class="input">
      <%= f.text_field :title, :placeholder => "Описание" %>
   </div>  
  </div>
  <div class="clearfix">
    <div class="input">
      <%= f.text_field :value, :placeholder => "Размер"%> м<sup>3</sup>
    </div>  
  </div>
  <div class="actions">
     <%= f.submit "Добавить", :class => "btn large primary", :style => "text-align:center;" %>
  </div>  
<% end %>

app/views/transactions/_transaction.html.erb
<tr>
    <td><%=transaction.boiler_room.name%></td>
    <td><%=transaction.consumer.name%></td>
    <td><%=transaction.value%> м<sup>3</sup></td>
    <td><%=show_status(transaction.status)%></td>
    <td><%=transaction.created_at.strftime("%R %D")%></td>
    <td><%=transaction.title%></td>
    <td>
    <div id="modal-from-dom<%=transaction.id%>" class="modal hide fade">
      <div class="modal-header">
        <a href="#" class="close">&times;</a>
        <h3 style="text-align:center;">Изменить</h3>
      </div>
      <div class="modal-body">
        <%= render "change_status_form", :transaction => transaction %> 
      </div>
    </div>
    <%= link_to 'Изменить', "#",{:class => "btn small",
                    "data-backdrop" => true,
                    "data-controls-modal" => "modal-from-dom#{transaction.id}",
                    "data-keyboard" => true } %>
    </td>
    <td><%= button_to 'Удалить', transaction, confirm: 'Вы уверены?', :method => :delete, :class => "btn small danger" %></td>
</tr>

app/views/transactions/index.html.erb
<div class="row show-grid">
  <div class="span2"><h3>Показать:</h3></div>
  <div class="span2"><%=link_to "Все", transactions_path, :class => "btn primary"%></div>
  <div class="span2"><%=link_to "Отправленные", transactions_path(:status => "send"), :class => "btn small"%></div>
  <div class="span2"><%=link_to "Полученные", transactions_path(:status => "received"), :class => "btn small success"%></div>   
  <div class="span2"><%=link_to "Расходуемые", transactions_path(:status => "use"), :class => "btn small warning"%></div>
  <div class="span2"><%=link_to "Израсходованные", transactions_path(:status => "finish"), :class => "btn small danger"%></div>
  <div class="span4" style="text-align:center;"><h4>Всего: <%=@transactions.map(&:value).inject(&:+)||0%> м<sup>3</sup></h4></div> 
</div>
<br />
<% if @transactions.size > 0 %>
<table class="zebra-striped" id="transactions">
  <thead> 
    <tr>
      <th>Котельная</th>
      <th>Потребитель</th>
      <th>Размер</th>
      <th>Статус</th>
      <th>Дата</th>
      <th>Комментарий</th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <%= render @transactions %>
  </tbody>
</table>
<% end %>

app/views/transactions/search.html.erb
<%= form_for @search, :url => search_transactions_path do |f| %>
  <div class="clearfix">
      <div class="inline-inputs">
            Поставки с
    	  <%= f.text_field :created_at_gteq, :class => "small" %>
           по 
        <%= f.text_field :created_at_lteq, :class => "small" %>
        <%= f.select :status_equals, [["Со статусом",""],["Отправлено","send" ],["Получено", "received"],["Расходуется", "use"],["Израсходовано", "finish"]] %>
        <%= f.select :boiler_room_id_equals,[["Из котельной",""]] + BoilerRoom.all.collect {|b| [ b.name, b.id ]} %>
        <%= f.select :consumer_id_equals, [["Потребителю",""]] + Consumer.all.collect {|b| [ b.name, b.id ]} %>
      </div> 
  </div>
  <div class="row">
    <div class="span5" style="text-align:center;">
      <%= f.submit "Найти", :class => "btn large primary", :size => 300 %>
     <% end %>
    </div>
    <div class="span5" style="text-align:center;">
       <%=link_to "Скачать XML", search_transactions_path(:format => :csv, :search => params[:search]), :class => "btn large success" if @transactions.size > 0 %>
     </div> 
     <div class="span5">
      <% if @transactions.size > 0 %>
        <h3>Всего: <%=@transactions.map(&:value).inject(&:+)%> м<sup>3</sup></h3>
      <% end %> 
     </div> 
  </div>
 <br />
 <% if @transactions.size > 0 %>
 <table class="zebra-striped" id="transactions">
  <thead> 
  <tr>
    <th>Котельная</th>
    <th>Потребитель</th>
    <th>Размер поставки</th>
    <th>Статус</th>
    <th>Дата</th>
    <th>Комментарий</th>
    <th></th>
    <th></th>
  </tr>
  </thead>
  <tbody>
    <%= render @transactions %>
  </tbody>
</table>
<% else %>
  <h1>Ничего не найдено</h1>
<% end %>